/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RegisterSpeakerRouteImport } from './routes/register.speaker'
import { Route as AdminSpeakersRouteImport } from './routes/admin.speakers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminAttendeesRouteImport } from './routes/admin.attendees'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RegisterSpeakerRoute = RegisterSpeakerRouteImport.update({
  id: '/register/speaker',
  path: '/register/speaker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendeesRoute = AdminAttendeesRouteImport.update({
  id: '/attendees',
  path: '/attendees',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/register/speaker': typeof RegisterSpeakerRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/register/speaker': typeof RegisterSpeakerRoute
  '/admin': typeof AdminIndexRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/attendees': typeof AdminAttendeesRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/register/speaker': typeof RegisterSpeakerRoute
  '/admin/': typeof AdminIndexRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/attendees'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/speakers'
    | '/register/speaker'
    | '/admin/'
    | '/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendees'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/speakers'
    | '/register/speaker'
    | '/admin'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/attendees'
    | '/admin/checkin'
    | '/admin/communications'
    | '/admin/login'
    | '/admin/reports'
    | '/admin/speakers'
    | '/register/speaker'
    | '/admin/'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RegisterSpeakerRoute: typeof RegisterSpeakerRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/register/speaker': {
      id: '/register/speaker'
      path: '/register/speaker'
      fullPath: '/register/speaker'
      preLoaderRoute: typeof RegisterSpeakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendees': {
      id: '/admin/attendees'
      path: '/attendees'
      fullPath: '/admin/attendees'
      preLoaderRoute: typeof AdminAttendeesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAttendeesRoute: typeof AdminAttendeesRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttendeesRoute: AdminAttendeesRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RegisterSpeakerRoute: RegisterSpeakerRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
